"""
SYNAPSE-X — Developer Child Agent
Generates backend service code, FastAPI scaffolds, endpoints, and route definitions.
"""

from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from typing import Any


def _generate_fastapi_scaffold(prompt: str, tasks: list[dict[str, Any]]) -> str:
    """Produce a syntactically valid FastAPI service scaffold."""

    # Extract meaningful identifiers from the prompt
    app_name = prompt.split()[1] if len(prompt.split()) > 1 else "service"
    app_name = "".join(c for c in app_name if c.isalnum()).lower() or "service"

    # Build CRUD endpoint stubs from the task graph
    endpoint_blocks: list[str] = []
    for task in tasks:
        if task.get("category") == "backend":
            slug = task["title"].lower().replace(" ", "_")[:30]
            endpoint_blocks.append(textwrap.dedent(f"""\
                @app.get("/{slug}")
                async def {slug}():
                    \"\"\"Auto-generated endpoint: {task['title']}\"\"\"
                    return {{"status": "ok", "task": "{task['title']}"}}
            """))

    if not endpoint_blocks:
        endpoint_blocks.append(textwrap.dedent("""\
            @app.get("/items")
            async def list_items():
                \"\"\"List all items.\"\"\"
                return {"items": []}

            @app.post("/items")
            async def create_item(name: str = "default"):
                \"\"\"Create a new item.\"\"\"
                return {"created": name}

            @app.get("/items/{item_id}")
            async def get_item(item_id: int):
                \"\"\"Get item by ID.\"\"\"
                return {"item_id": item_id, "name": "sample"}

            @app.delete("/items/{item_id}")
            async def delete_item(item_id: int):
                \"\"\"Delete item by ID.\"\"\"
                return {"deleted": item_id}
        """))

    endpoints_code = "\n".join(endpoint_blocks)

    code = textwrap.dedent(f"""\
        \"\"\"
        Auto-generated FastAPI service: {app_name}
        Generated by SYNAPSE-X Developer Agent
        \"\"\"
        from fastapi import FastAPI, HTTPException
        from pydantic import BaseModel
        from typing import Optional, List
        import logging

        logging.basicConfig(level=logging.INFO)
        logger = logging.getLogger("{app_name}")

        app = FastAPI(
            title="{app_name.capitalize()} Service",
            description="Auto-generated by SYNAPSE-X Dev Agent",
            version="0.1.0",
        )


        class Item(BaseModel):
            id: Optional[int] = None
            name: str
            description: Optional[str] = None


        @app.get("/")
        async def root():
            return {{"service": "{app_name}", "status": "running"}}


        @app.get("/health")
        async def health():
            return {{"healthy": True}}


        {endpoints_code}
    """)
    return code


def _generate_route_definitions(tasks: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Generate a list of route definition dicts."""
    routes: list[dict[str, str]] = [
        {"method": "GET", "path": "/", "description": "Root / health check"},
        {"method": "GET", "path": "/health", "description": "Health probe"},
    ]
    for task in tasks:
        if task.get("category") == "backend":
            slug = task["title"].lower().replace(" ", "_")[:30]
            routes.append({
                "method": "GET",
                "path": f"/{slug}",
                "description": task["title"],
            })
    if len(routes) == 2:
        routes.extend([
            {"method": "GET", "path": "/items", "description": "List items"},
            {"method": "POST", "path": "/items", "description": "Create item"},
            {"method": "GET", "path": "/items/{item_id}", "description": "Get item"},
            {"method": "DELETE", "path": "/items/{item_id}", "description": "Delete item"},
        ])
    return routes


# ── Public API ───────────────────────────────────────────────────────────────

def generate(prompt: str, task_graph: list[dict[str, Any]]) -> dict[str, Any]:
    """
    Generate backend code artifacts from the parent agent's task graph.

    Returns:
        dict with keys: service_code, route_definitions, status
    """
    backend_tasks = [t for t in task_graph if t.get("category") == "backend"]

    service_code = _generate_fastapi_scaffold(prompt, backend_tasks)
    route_defs = _generate_route_definitions(backend_tasks)

    return {
        "agent": "dev_agent",
        "service_code": service_code,
        "route_definitions": route_defs,
        "status": {
            "success": True,
            "files_generated": 1,
            "endpoints_created": len(route_defs),
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    }
